<template>
    <Card class="name-picker">
        <slot></slot>
        <ul class="names-list">
            <li
                v-for="(nameTableKey, index) in Object.keys(nameTables)"
                :key="index"
                @click="toggleNameTable(nameTableKey)"
            >
                <i :class="activeNameTables.includes(nameTableKey) ? 'fas fa-check-square' : 'far fa-square'"></i>
                <span v-html="nameCategoryLabelFunction(nameTableKey)"></span>
            </li>
        </ul>
        <div class="flex">
            <Button @click="onClickGenerateName" :disabled="activeNameTables.length === 0">
                <i class="fas fa-magic"></i>
                <span>{{ t('generate') }}</span>
            </Button>
            <Button @click="onClickRollName" :disabled="activeNameTables.length === 0">
                <i class="fas fa-random"></i>
                <span>{{ t('roll') }}</span>
            </Button>
        </div>
    </Card>
</template>

<script setup lang="ts">
import { t } from '@/i18n/locale';
import { generateMarkovName } from '@/utils/adventurer-util';
import { ref, watch, onMounted } from 'vue';

const props = defineProps({
    id: {
        // Use the id to store the name table choices locally
        type: String,
        required: true
    },
    nameTables: {
        // { "german": ["hans fischer", "klaus meier" ...], "french": ["jean dupont", "pierre durand" ...] }
        type: Object as () => Record<string, string[]>,
        required: true
    },
    name: {
        // The name generated by the name tables
        type: String,
        required: true
    },
    nameCategoryLabelFunction: {
        // Function to get the label for the name category
        type: Function as unknown as () => (item: string) => string,
        required: true
    }
});

const activeNameTables = ref<string[]>([]);

const emit = defineEmits(['update:name']);

const localStorageKey = `name-picker.${props.id}`;

onMounted(() => {
    const stored = localStorage.getItem(localStorageKey);
    if (stored) {
        try {
            const parsed = JSON.parse(stored);
            if (Array.isArray(parsed)) {
                activeNameTables.value = parsed;
            }
        } catch (e) {
            // ignore parse errors
        }
    }
});

watch(
    activeNameTables,
    (val) => {
        localStorage.setItem(localStorageKey, JSON.stringify(val));
    },
    { deep: true }
);

function toggleNameTable(nameTableKey: string) {
    if (activeNameTables.value.includes(nameTableKey))
        activeNameTables.value = activeNameTables.value.filter((table) => table !== nameTableKey);
    else activeNameTables.value.push(nameTableKey);
}

function onClickGenerateName() {
    // Generate a name using the selected name tables
    const allNames: string[] = [];
    activeNameTables.value.forEach((nameTableKey) => {
        const nameTableData = props.nameTables[nameTableKey as keyof typeof props.nameTables];
        allNames.push(...nameTableData);
    });

    const generatedName = generateMarkovName(allNames, 3);
    if (generatedName) emit('update:name', generatedName);
}

function onClickRollName() {
    // Pick a random name from the selected name tables
    const allNames: string[] = [];
    activeNameTables.value.forEach((nameTableKey) => {
        const nameTableData = props.nameTables[nameTableKey as keyof typeof props.nameTables];
        allNames.push(...nameTableData);
    });

    const randomName = allNames[Math.floor(Math.random() * allNames.length)];
    if (randomName) emit('update:name', randomName);
}
</script>

<style scoped lang="scss">
.card {
    width: 100%;

    > ul.names-list {
        width: 100%;
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(10rem, 1fr));
        gap: 1rem;
        margin-bottom: 0.4rem;

        > li {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            cursor: pointer;

            > * {
                white-space: nowrap;
                overflow: hidden;
                text-overflow: ellipsis;
            }

            i {
                font-size: 1.6rem;
            }
        }
    }
}
</style>
